export type WEngine = {
  slug: string;
  name: string;
  rank: "S" | "A" | "B";
  specialty: string; // 強攻/異常/撃破/支援/防護/命破
  baseAtk: number;
  advancedStat: string;
  effect: string;
  motifAgent?: string;
  recommendedAgents: string[];
};

export const W_ENGINES: WEngine[] = [
  // ── S級 強攻 ──
  {
    slug: "lonely-light-colorful-cloud",
    name: "孤光彩雲",
    rank: "S",
    specialty: "強攻",
    baseAtk: 743,
    advancedStat: "会心ダメージ+48%",
    effect: "物理耐性を無視。通常攻撃・ダッシュ攻撃のダメージアップ。",
    motifAgent: "葉瞬光",
    recommendedAgents: ["葉瞬光"],
  },
  {
    slug: "deep-sea-visitor",
    name: "ディープシー・ビジター",
    rank: "S",
    specialty: "強攻",
    baseAtk: 713,
    advancedStat: "会心率+24%",
    effect: "氷属性ダメージ+25%。通常攻撃命中時、会心率がさらにアップ。",
    motifAgent: "エレン・ジョー",
    recommendedAgents: ["エレン・ジョー"],
  },
  {
    slug: "riot-suppressor-mark-vi",
    name: "サプレッサーⅥ型",
    rank: "S",
    specialty: "強攻",
    baseAtk: 713,
    advancedStat: "会心ダメージ+48%",
    effect: "会心率+15%。エーテル属性ダメージ+35%。",
    motifAgent: "朱鳶",
    recommendedAgents: ["朱鳶"],
  },
  {
    slug: "lingering-blue-cage",
    name: "残心の青籠",
    rank: "S",
    specialty: "強攻",
    baseAtk: 713,
    advancedStat: "会心ダメージ+48%",
    effect: "電気属性ダメージ+40%。会心率アップ効果。",
    motifAgent: "浅羽悠真",
    recommendedAgents: ["浅羽悠真"],
  },
  {
    slug: "heartstring-nocturne",
    name: "心弦のノクターン",
    rank: "S",
    specialty: "強攻",
    baseAtk: 713,
    advancedStat: "会心率+24%",
    effect: "炎耐性を無視。スキル使用時にダメージバフ。",
    motifAgent: "イヴリン",
    recommendedAgents: ["イヴリン"],
  },
  {
    slug: "pure-sacrifice",
    name: "純然たる犠牲",
    rank: "S",
    specialty: "強攻",
    baseAtk: 713,
    advancedStat: "会心ダメージ+48%",
    effect: "会心ダメージスタック。電気属性ダメージ+20%。",
    motifAgent: "0号・アンビー",
    recommendedAgents: ["0号・アンビー"],
  },
  {
    slug: "driven-seed",
    name: "駆動する種",
    rank: "S",
    specialty: "強攻",
    baseAtk: 713,
    advancedStat: "会心率+24%",
    effect: "電気属性ダメージアップ。防御無視効果。",
    motifAgent: "「シード」",
    recommendedAgents: ["「シード」"],
  },
  {
    slug: "thousand-face-sunset",
    name: "千面の落日",
    rank: "S",
    specialty: "強攻",
    baseAtk: 713,
    advancedStat: "会心率+24%",
    effect: "氷耐性を無視する効果。",
    motifAgent: "ヒューゴ",
    recommendedAgents: ["ヒューゴ"],
  },
  {
    slug: "fury-gun-roar",
    name: "憤怒の銃騒",
    rank: "S",
    specialty: "強攻",
    baseAtk: 713,
    advancedStat: "エネルギー自動回復+60%",
    effect: "炎属性ダメージの防御無視効果。",
    motifAgent: "オルペウス&「鬼火」",
    recommendedAgents: ["オルペウス&「鬼火」"],
  },
  {
    slug: "brimstone",
    name: "ブリムストーン",
    rank: "S",
    specialty: "強攻",
    baseAtk: 684,
    advancedStat: "攻撃力+30%",
    effect: "通常攻撃・ダッシュ攻撃・回避反撃命中時に攻撃力+3.5%（最大8スタック）。",
    motifAgent: "「11号」",
    recommendedAgents: ["「11号」", "ビリー"],
  },
  {
    slug: "steel-cushion",
    name: "鋼の肉球",
    rank: "S",
    specialty: "強攻",
    baseAtk: 684,
    advancedStat: "会心率+24%",
    effect: "物理属性ダメージ+20%。背面から攻撃時、与ダメージがさらにアップ。",
    motifAgent: "猫又",
    recommendedAgents: ["猫又"],
  },
  // ── S級 異常 ──
  {
    slug: "hail-star-palace",
    name: "あられ落つ星殿",
    rank: "S",
    specialty: "異常",
    baseAtk: 743,
    advancedStat: "会心率+24%",
    effect: "氷属性ダメージスタック効果。EXスキル使用後にダメージバフ。",
    motifAgent: "星見雅",
    recommendedAgents: ["星見雅"],
  },
  {
    slug: "polished-edge",
    name: "磨き抜かれた切っ先",
    rank: "S",
    specialty: "異常",
    baseAtk: 713,
    advancedStat: "異常マスタリー+90",
    effect: "物理ダメージアップ。異常蓄積効率+40%。",
    motifAgent: "ジェーン・ドゥ",
    recommendedAgents: ["ジェーン・ドゥ"],
  },
  {
    slug: "flowing-sage",
    name: "刻流の賢者",
    rank: "S",
    specialty: "異常",
    baseAtk: 713,
    advancedStat: "攻撃力+30%",
    effect: "異常マスタリー375以上で混沌ダメージ+25%。",
    motifAgent: "月城柳",
    recommendedAgents: ["月城柳"],
  },
  {
    slug: "burning-shaker",
    name: "バーニング・シェイカー",
    rank: "S",
    specialty: "異常",
    baseAtk: 713,
    advancedStat: "攻撃力+30%",
    effect: "ダメージスタック効果。異常マスタリー+50。",
    motifAgent: "バーニス",
    recommendedAgents: ["バーニス"],
  },
  {
    slug: "ten-star",
    name: "十面百錬の星",
    rank: "S",
    specialty: "異常",
    baseAtk: 713,
    advancedStat: "攻撃力+30%",
    effect: "強撃後に物理属性ダメージアップ。",
    motifAgent: "アリス",
    recommendedAgents: ["アリス"],
  },
  {
    slug: "bird-dream-wings",
    name: "鳥は夢へと羽ばたいて",
    rank: "S",
    specialty: "異常",
    baseAtk: 713,
    advancedStat: "異常マスタリー+90",
    effect: "異常蓄積効率+40%。エーテル属性ダメージ強化。",
    motifAgent: "ビビアン",
    recommendedAgents: ["ビビアン"],
  },
  {
    slug: "fusion-compiler",
    name: "複合コンパイラ",
    rank: "S",
    specialty: "異常",
    baseAtk: 684,
    advancedStat: "貫通率+24%",
    effect: "攻撃力+12%。EXスキル・連携スキル使用後に異常マスタリーがアップ。汎用異常音動機。",
    motifAgent: "グレース",
    recommendedAgents: ["グレース", "バーニス", "ジェーン・ドゥ", "月城柳"],
  },
  // ── S級 撃破 ──
  {
    slug: "jade-pot-ice",
    name: "玉壺青氷",
    rank: "S",
    specialty: "撃破",
    baseAtk: 713,
    advancedStat: "衝撃力+18%",
    effect: "スタック獲得時にチーム全体のダメージを強化。",
    motifAgent: "青衣",
    recommendedAgents: ["青衣"],
  },
  {
    slug: "flame-crown",
    name: "炎心の桂冠",
    rank: "S",
    specialty: "撃破",
    baseAtk: 713,
    advancedStat: "衝撃力+18%",
    effect: "デバフスタックごとに氷・炎属性の会心ダメージアップ。",
    motifAgent: "ライト",
    recommendedAgents: ["ライト"],
  },
  {
    slug: "fortune-tiger",
    name: "招福の虎炉",
    rank: "S",
    specialty: "撃破",
    baseAtk: 713,
    advancedStat: "攻撃力+30%",
    effect: "撃破値アップ。チーム全体のダメージバフ。",
    motifAgent: "橘福福",
    recommendedAgents: ["橘福福"],
  },
  {
    slug: "soul-reaper",
    name: "奪魂の瞑目",
    rank: "S",
    specialty: "撃破",
    baseAtk: 713,
    advancedStat: "会心率+24%",
    effect: "敵の防御-25%。衝撃力アップ。",
    motifAgent: "「トリガー」",
    recommendedAgents: ["「トリガー」"],
  },
  {
    slug: "last-night-call",
    name: "昨夜からの着信",
    rank: "S",
    specialty: "撃破",
    baseAtk: 713,
    advancedStat: "会心率+24%",
    effect: "撃破値アップ。チーム全体の会心ダメージバフ。",
    motifAgent: "ダイアリン",
    recommendedAgents: ["ダイアリン"],
  },
  {
    slug: "hellfire-gears",
    name: "燃獄ギア",
    rank: "S",
    specialty: "撃破",
    baseAtk: 684,
    advancedStat: "衝撃力+18%",
    effect: "強化特殊スキルで衝撃力アップ。汎用撃破音動機。",
    motifAgent: "クレタ",
    recommendedAgents: ["クレタ", "青衣", "ライカン"],
  },
  {
    slug: "the-restrained",
    name: "拘縛されし者",
    rank: "S",
    specialty: "撃破",
    baseAtk: 684,
    advancedStat: "衝撃力+18%",
    effect: "通常攻撃ダメージ・撃破値スタック。",
    motifAgent: "ライカン",
    recommendedAgents: ["ライカン", "青衣"],
  },
  // ── S級 支援 ──
  {
    slug: "song-of-feelings",
    name: "想いが織りなす歌",
    rank: "S",
    specialty: "支援",
    baseAtk: 713,
    advancedStat: "エネルギー自動回復+60%",
    effect: "強化特殊スキル後にチーム全体のダメージバフ。",
    motifAgent: "千夏",
    recommendedAgents: ["千夏"],
  },
  {
    slug: "vanity-beauty",
    name: "優美のヴァニティ",
    rank: "S",
    specialty: "支援",
    baseAtk: 713,
    advancedStat: "攻撃力+30%",
    effect: "エネルギー消費後にチーム全体のダメージバフ。",
    motifAgent: "アストラ・ヤオ",
    recommendedAgents: ["アストラ・ヤオ"],
  },
  {
    slug: "tanuki-transformation",
    name: "狸の七変化",
    rank: "S",
    specialty: "支援",
    baseAtk: 713,
    advancedStat: "エネルギー自動回復+60%",
    effect: "チーム全体の異常マスタリーアップ。",
    motifAgent: "浮波柚葉",
    recommendedAgents: ["浮波柚葉"],
  },
  {
    slug: "furnace-dream-song",
    name: "炉で歌い上げられる夢",
    rank: "S",
    specialty: "支援",
    baseAtk: 713,
    advancedStat: "HP+30%",
    effect: "チーム全体のダメージバフ。HP上限アップ。",
    motifAgent: "リュシア",
    recommendedAgents: ["リュシア"],
  },
  {
    slug: "weeping-cradle",
    name: "啜り泣くゆりかご",
    rank: "S",
    specialty: "支援",
    baseAtk: 684,
    advancedStat: "貫通率+24%",
    effect: "チーム対象ダメージアップ。攻撃命中でダメージスタック。汎用支援音動機。",
    motifAgent: "リナ",
    recommendedAgents: ["リナ", "ニコ", "蒼角", "ルーシー"],
  },
  // ── S級 防護 ──
  {
    slug: "snow-rabbit",
    name: "甘さ控えめ雪うさぎ",
    rank: "S",
    specialty: "防護",
    baseAtk: 713,
    advancedStat: "HP+30%",
    effect: "チーム攻撃力・HPアップ。会心ダメージバフ。",
    motifAgent: "照",
    recommendedAgents: ["照"],
  },
  {
    slug: "rushing-fang",
    name: "猛進するキバ",
    rank: "S",
    specialty: "防護",
    baseAtk: 713,
    advancedStat: "衝撃力+18%",
    effect: "シールド+30%。チーム全体のダメージ+18%、撃破値+12%。",
    motifAgent: "シーザー",
    recommendedAgents: ["シーザー"],
  },
  // ── S級 命破 ──
  {
    slug: "blue-avian-cage",
    name: "青溟の鳥籠",
    rank: "S",
    specialty: "命破",
    baseAtk: 743,
    advancedStat: "HP+30%",
    effect: "エーテル属性ダメージアップ。貫通率アップ。",
    motifAgent: "儀玄",
    recommendedAgents: ["儀玄"],
  },
  {
    slug: "diamond-fury-crown",
    name: "金剛不壊怒髪衝冠",
    rank: "S",
    specialty: "命破",
    baseAtk: 713,
    advancedStat: "HP+30%",
    effect: "会心率アップ。強化特殊スキルで炎属性貫通ダメージアップ。",
    motifAgent: "盤岳",
    recommendedAgents: ["盤岳"],
  },
  {
    slug: "siren-cradle",
    name: "セイレーンクレードル",
    rank: "S",
    specialty: "命破",
    baseAtk: 713,
    advancedStat: "HP+30%",
    effect: "HP減少時に氷属性貫通ダメージアップ。",
    motifAgent: "イドリー",
    recommendedAgents: ["イドリー"],
  },
  // ── A級 強攻 ──
  {
    slug: "fake-starlight-engine",
    name: "なんちゃってスターライトエンジン",
    rank: "A",
    specialty: "強攻",
    baseAtk: 624,
    advancedStat: "攻撃力+25%",
    effect: "6m以上離れた敵に物理ダメージ+36%。",
    motifAgent: "ビリー",
    recommendedAgents: ["ビリー"],
  },
  {
    slug: "housekeeper",
    name: "ハウスキーパー",
    rank: "A",
    specialty: "強攻",
    baseAtk: 624,
    advancedStat: "攻撃力+25%",
    effect: "強化スキル命中で物理ダメージアップスタック。",
    motifAgent: "カリン",
    recommendedAgents: ["カリン"],
  },
  {
    slug: "drill-rig-red-axis",
    name: "ドリルリグ-レッドシャフト",
    rank: "A",
    specialty: "強攻",
    baseAtk: 624,
    advancedStat: "エネルギー自動回復+50%",
    effect: "強化スキル後に通常・ダッシュ攻撃の電気ダメージ+50%。",
    motifAgent: "アンドー",
    recommendedAgents: ["アンドー"],
  },
  {
    slug: "gilded-blossom",
    name: "金メッキの花信",
    rank: "A",
    specialty: "強攻",
    baseAtk: 594,
    advancedStat: "攻撃力+25%",
    effect: "攻撃力+6%。強化スキルダメージ+15%。",
    recommendedAgents: ["「11号」"],
  },
  {
    slug: "starlight-engine",
    name: "スターライトエンジン",
    rank: "A",
    specialty: "強攻",
    baseAtk: 594,
    advancedStat: "攻撃力+25%",
    effect: "回避反撃・支援攻撃発動時に攻撃力+12%。",
    recommendedAgents: ["猫又", "エレン・ジョー"],
  },
  {
    slug: "street-superstar",
    name: "ストリートスター",
    rank: "A",
    specialty: "強攻",
    baseAtk: 594,
    advancedStat: "攻撃力+25%",
    effect: "チーム連携スタックで終結スキルダメージアップ。",
    recommendedAgents: ["ビリー"],
  },
  {
    slug: "cannon-rotor",
    name: "キャノンローラー",
    rank: "A",
    specialty: "強攻",
    baseAtk: 594,
    advancedStat: "会心率+20%",
    effect: "攻撃力+7.5%。会心時に追加ダメージ。",
    recommendedAgents: ["猫又", "エレン・ジョー"],
  },
  {
    slug: "forte-desire",
    name: "強音デザイア",
    rank: "A",
    specialty: "強攻",
    baseAtk: 594,
    advancedStat: "会心率+20%",
    effect: "強化・連携スキル命中で攻撃力アップ。異常状態の敵に効果倍増。",
    recommendedAgents: ["「11号」", "猫又"],
  },
  // ── A級 異常 ──
  {
    slug: "growl-my-car",
    name: "グロウル・マイ・カー",
    rank: "A",
    specialty: "異常",
    baseAtk: 624,
    advancedStat: "攻撃力+25%",
    effect: "スキル使用で攻撃力・異常マスタリー・異常蓄積を交互にバフ。",
    motifAgent: "パイパー",
    recommendedAgents: ["パイパー"],
  },
  {
    slug: "rainforest-gourmet",
    name: "密林の食いしん坊",
    rank: "A",
    specialty: "異常",
    baseAtk: 594,
    advancedStat: "異常マスタリー+75",
    effect: "エネルギー消費で攻撃力アップ。",
    recommendedAgents: ["グレース", "バーニス"],
  },
  {
    slug: "electro-lip-gloss",
    name: "電撃リップグロス",
    rank: "A",
    specialty: "異常",
    baseAtk: 594,
    advancedStat: "異常マスタリー+75",
    effect: "攻撃力+10%。異常状態の敵へのダメージアップ。",
    recommendedAgents: ["グレース"],
  },
  {
    slug: "twin-tears",
    name: "双生の涙",
    rank: "A",
    specialty: "異常",
    baseAtk: 594,
    advancedStat: "攻撃力+25%",
    effect: "味方が異常付与時に異常マスタリーアップスタック。",
    recommendedAgents: ["月城柳", "バーニス"],
  },
  // ── A級 撃破 ──
  {
    slug: "demara-battery-ii",
    name: "デマラ式電池Ⅱ型",
    rank: "A",
    specialty: "撃破",
    baseAtk: 624,
    advancedStat: "衝撃力+15%",
    effect: "電気属性ダメージ+15%。回避時にエネルギー回復。",
    motifAgent: "アンビー",
    recommendedAgents: ["アンビー"],
  },
  {
    slug: "paper-cutter",
    name: "ペーパーカッター",
    rank: "A",
    specialty: "撃破",
    baseAtk: 624,
    advancedStat: "衝撃力+15%",
    effect: "追加攻撃で物理ダメージと撃破値アップ。",
    motifAgent: "プルクラ",
    recommendedAgents: ["プルクラ"],
  },
  {
    slug: "precious-fossilized-core",
    name: "貴重な石化コア",
    rank: "A",
    specialty: "撃破",
    baseAtk: 594,
    advancedStat: "衝撃力+15%",
    effect: "敵HPに応じて撃破値アップ。",
    recommendedAgents: ["ライカン", "クレタ"],
  },
  {
    slug: "cutting-board-carp",
    name: "まな板の鯉",
    rank: "A",
    specialty: "撃破",
    baseAtk: 594,
    advancedStat: "エネルギー自動回復+50%",
    effect: "エネルギー量に応じて衝撃力アップ。",
    recommendedAgents: ["アンビー", "クレタ"],
  },
  {
    slug: "six-shooter",
    name: "シックスシューター",
    rank: "A",
    specialty: "撃破",
    baseAtk: 594,
    advancedStat: "衝撃力+15%",
    effect: "強化スキルでパワースタック。撃破値に変換。",
    recommendedAgents: ["ライカン"],
  },
  // ── A級 支援 ──
  {
    slug: "shy-evil-face",
    name: "恥じらう悪面",
    rank: "A",
    specialty: "支援",
    baseAtk: 624,
    advancedStat: "攻撃力+25%",
    effect: "氷属性ダメージ+15%。強化スキルでチーム攻撃力アップ。",
    motifAgent: "蒼角",
    recommendedAgents: ["蒼角"],
  },
  {
    slug: "rowdy-bombardum",
    name: "喧嘩腰のボンバルダム",
    rank: "A",
    specialty: "支援",
    baseAtk: 624,
    advancedStat: "エネルギー自動回復+50%",
    effect: "味方が敵に攻撃命中でチーム攻撃力アップ。",
    motifAgent: "ルーシー",
    recommendedAgents: ["ルーシー"],
  },
  {
    slug: "the-vault",
    name: "ザ・ボールト",
    rank: "A",
    specialty: "支援",
    baseAtk: 624,
    advancedStat: "エネルギー自動回復+50%",
    effect: "エーテル属性スキル命中でチームダメージ+15%。",
    motifAgent: "ニコ",
    recommendedAgents: ["ニコ"],
  },
  {
    slug: "slice-of-time",
    name: "歳月の薄片",
    rank: "A",
    specialty: "支援",
    baseAtk: 594,
    advancedStat: "貫通率+20%",
    effect: "味方のアクションでエネルギー回復。",
    recommendedAgents: ["ルーシー", "蒼角"],
  },
  {
    slug: "kaboom-the-cannon",
    name: "ゲームボール",
    rank: "A",
    specialty: "支援",
    baseAtk: 594,
    advancedStat: "エネルギー自動回復+50%",
    effect: "属性有利時にチーム会心率アップ。",
    recommendedAgents: ["ニコ", "蒼角"],
  },
  // ── A級 防護 ──
  {
    slug: "bigger-cylinder",
    name: "ビガー・シリンダー",
    rank: "A",
    specialty: "防護",
    baseAtk: 624,
    advancedStat: "防御力+40%",
    effect: "ダメージ軽減。反撃時に確定会心。",
    motifAgent: "ベン",
    recommendedAgents: ["ベン"],
  },
  {
    slug: "order-protector",
    name: "秩序の守り手・特化型",
    rank: "A",
    specialty: "防護",
    baseAtk: 624,
    advancedStat: "攻撃力+25%",
    effect: "シールド展開でエネルギー回復。異常蓄積アップ。",
    motifAgent: "セス",
    recommendedAgents: ["セス"],
  },
  {
    slug: "thunder-bagua",
    name: "雷鳴が如き八卦",
    rank: "A",
    specialty: "防護",
    baseAtk: 624,
    advancedStat: "攻撃力+25%",
    effect: "特殊スキルダメージアップ。被ダメ・回復時にエネルギー回復。",
    motifAgent: "潘引壺",
    recommendedAgents: ["潘引壺"],
  },
  {
    slug: "official-transformer",
    name: "正規版変身装置",
    rank: "A",
    specialty: "防護",
    baseAtk: 594,
    advancedStat: "HP+25%",
    effect: "HPバフ。被ダメ時に衝撃力アップ。",
    recommendedAgents: ["シーザー", "ベン"],
  },
  {
    slug: "bunny-band",
    name: "ラビットチャージャー",
    rank: "A",
    specialty: "防護",
    baseAtk: 594,
    advancedStat: "防御力+40%",
    effect: "シールド展開中にHP・攻撃力アップ。",
    recommendedAgents: ["ベン", "セス"],
  },
  {
    slug: "hot-spring",
    name: "ホットスプリング",
    rank: "A",
    specialty: "防護",
    baseAtk: 594,
    advancedStat: "攻撃力+25%",
    effect: "ダメージ軽減。被ダメ時にエネルギー回復。",
    recommendedAgents: ["セス", "潘引壺"],
  },
  {
    slug: "light-shadow-cut",
    name: "光と影のカット",
    rank: "A",
    specialty: "防護",
    baseAtk: 594,
    advancedStat: "衝撃力+15%",
    effect: "味方HP50%以上でダメージ軽減・瘴気軽減。",
    recommendedAgents: ["シーザー"],
  },
  // ── A級 命破 ──
  {
    slug: "burning-dusk",
    name: "燔火の朧夜",
    rank: "A",
    specialty: "命破",
    baseAtk: 624,
    advancedStat: "HP+25%",
    effect: "炎ダメージアップ。HP低下時に会心率アップ。",
    motifAgent: "狛野真斗",
    recommendedAgents: ["狛野真斗"],
  },
  {
    slug: "blue-wave-spirit",
    name: "蒼き波の霊器",
    rank: "A",
    specialty: "命破",
    baseAtk: 594,
    advancedStat: "HP+25%",
    effect: "強化特殊スキル使用でダメージアップスタック（最大3重）。",
    recommendedAgents: ["盤岳", "儀玄"],
  },
  {
    slug: "magic-cube-puzzle",
    name: "魔法の立体パズル",
    rank: "A",
    specialty: "命破",
    baseAtk: 594,
    advancedStat: "攻撃力+25%",
    effect: "特殊スキルの会心ダメージアップ。弱体敵への追加ダメージ。",
    recommendedAgents: ["イドリー"],
  },
  {
    slug: "electro-walk",
    name: "エレクトロウォーク",
    rank: "A",
    specialty: "命破",
    baseAtk: 594,
    advancedStat: "HP+25%",
    effect: "連携・終結スキルで貫通スタック付与。",
    recommendedAgents: ["狛野真斗"],
  },
  // ── B級 ──
  {
    slug: "moon-phase-full",
    name: "「月相」-望",
    rank: "B",
    specialty: "強攻",
    baseAtk: 475,
    advancedStat: "攻撃力+20%",
    effect: "基礎強攻向け音動機。",
    recommendedAgents: [],
  },
  {
    slug: "moon-phase-wane",
    name: "「月相」-晦",
    rank: "B",
    specialty: "強攻",
    baseAtk: 475,
    advancedStat: "攻撃力+20%",
    effect: "基礎強攻向け音動機。",
    recommendedAgents: [],
  },
  {
    slug: "moon-phase-new",
    name: "「月相」-朔",
    rank: "B",
    specialty: "強攻",
    baseAtk: 475,
    advancedStat: "会心率+16%",
    effect: "会心特化の基礎強攻向け音動機。",
    recommendedAgents: [],
  },
  {
    slug: "torrent-gun",
    name: "激流銃型",
    rank: "B",
    specialty: "撃破",
    baseAtk: 475,
    advancedStat: "攻撃力+20%",
    effect: "基礎撃破向け音動機。",
    recommendedAgents: [],
  },
  {
    slug: "torrent-arrow",
    name: "激流矢型",
    rank: "B",
    specialty: "撃破",
    baseAtk: 475,
    advancedStat: "衝撃力+12%",
    effect: "衝撃力特化の基礎撃破向け音動機。",
    recommendedAgents: [],
  },
  {
    slug: "torrent-axe",
    name: "激流斧型",
    rank: "B",
    specialty: "撃破",
    baseAtk: 475,
    advancedStat: "エネルギー自動回復+40%",
    effect: "エネルギー回復特化の基礎撃破向け音動機。",
    recommendedAgents: [],
  },
  {
    slug: "echo-type-i",
    name: "残響Ⅰ型",
    rank: "B",
    specialty: "支援",
    baseAtk: 475,
    advancedStat: "攻撃力+20%",
    effect: "基礎支援向け音動機。",
    recommendedAgents: [],
  },
  {
    slug: "echo-type-ii",
    name: "残響Ⅱ型",
    rank: "B",
    specialty: "支援",
    baseAtk: 475,
    advancedStat: "エネルギー自動回復+40%",
    effect: "エネルギー回復特化の基礎支援向け音動機。",
    recommendedAgents: [],
  },
  {
    slug: "echo-type-iii",
    name: "残響Ⅲ型",
    rank: "B",
    specialty: "支援",
    baseAtk: 475,
    advancedStat: "HP+20%",
    effect: "HP特化の基礎支援向け音動機。",
    recommendedAgents: [],
  },
  {
    slug: "magnetic-storm-i",
    name: "磁気嵐壱式",
    rank: "B",
    specialty: "異常",
    baseAtk: 475,
    advancedStat: "攻撃力+20%",
    effect: "基礎異常向け音動機。",
    recommendedAgents: [],
  },
  {
    slug: "magnetic-storm-ii",
    name: "磁気嵐弐式",
    rank: "B",
    specialty: "異常",
    baseAtk: 475,
    advancedStat: "異常マスタリー+60",
    effect: "異常マスタリー特化の基礎異常向け音動機。",
    recommendedAgents: [],
  },
  {
    slug: "magnetic-storm-iii",
    name: "磁気嵐参式",
    rank: "B",
    specialty: "異常",
    baseAtk: 475,
    advancedStat: "貫通率+16%",
    effect: "貫通特化の基礎異常向け音動機。",
    recommendedAgents: [],
  },
  {
    slug: "identity-standard",
    name: "恒等式本格",
    rank: "B",
    specialty: "防護",
    baseAtk: 475,
    advancedStat: "防御力+32%",
    effect: "基礎防護向け音動機。",
    recommendedAgents: [],
  },
  {
    slug: "identity-variant",
    name: "恒等式変格",
    rank: "B",
    specialty: "防護",
    baseAtk: 475,
    advancedStat: "防御力+32%",
    effect: "基礎防護向け音動機。",
    recommendedAgents: [],
  },
  {
    slug: "ash-blue",
    name: "灰燼蒼藍",
    rank: "B",
    specialty: "命破",
    baseAtk: 475,
    advancedStat: "HP+20%",
    effect: "基礎命破向け音動機。",
    recommendedAgents: [],
  },
];

// slug → WEngine ルックアップマップ
const _slugMap = new Map<string, WEngine>();
for (const engine of W_ENGINES) {
  _slugMap.set(engine.slug, engine);
}
export const W_ENGINE_MAP: ReadonlyMap<string, WEngine> = _slugMap;

// 名前 → WEngine ルックアップマップ
const _nameMap = new Map<string, WEngine>();
for (const engine of W_ENGINES) {
  _nameMap.set(engine.name, engine);
}
export const W_ENGINE_NAME_MAP: ReadonlyMap<string, WEngine> = _nameMap;

export function getWEngineBySlug(slug: string): WEngine | undefined {
  return W_ENGINE_MAP.get(slug);
}

export function getAllWEngines(): WEngine[] {
  return W_ENGINES;
}

export function getWEnginesBySpecialty(specialty: string): WEngine[] {
  return W_ENGINES.filter((e) => e.specialty === specialty);
}

export function getWEnginesByRank(rank: "S" | "A" | "B"): WEngine[] {
  return W_ENGINES.filter((e) => e.rank === rank);
}

export const W_ENGINE_SPECIALTIES = ["強攻", "異常", "撃破", "支援", "防護", "命破"] as const;
